### ISSUE TITLE
purpose of this line of code not clear

### ISSUE THREAD

**Issue by tokami** [tokami/StockMonitoringTool#10]
https://github.com/tokami/StockMonitoringTool/blob/bad1210832b434e477c157c99addc38066a1dcd2/assets/tropFishR/algorithms/run_elefan_ga.R#L129

The purpose of this line of code is not clear. It implies that in a data set spanning multiple years, this line of code uses the second to last year is used for the estimation of total mortality. It its important that this variable becomes an input to be set by the user.

**Comment by aenieblas** [comment]
can default inputs be customised for the dataset programmatically? otherwise how does the user choose the values?
