### ISSUE TITLE
use FM + selectivity for fishing mortality at length

### ISSUE THREAD

**Issue by tokami** [tokami/StockMonitoringTool#11]
https://github.com/tokami/StockMonitoringTool/blob/bad1210832b434e477c157c99addc38066a1dcd2/assets/tropFishR/algorithms/run_elefan_ga.R#L201

Preliminary results have shown that fishing mortality and selectivity (assuming logistic curve) are more robust than F-at-length estimation from VPA. Further simulations are needed, but so far consider using catch curve to define this vector.

**Comment by aenieblas** [comment]
agreed.
