### ISSUE TITLE
parameters of length-weight relationship

### ISSUE THREAD

**Issue by tokami** [tokami/StockMonitoringTool#14]
https://github.com/tokami/StockMonitoringTool/blob/bad1210832b434e477c157c99addc38066a1dcd2/assets/tropFishR/algorithms/run_elefan_ga.R#L172

Parameters a and b (line 174) used in VPA and YPR should be user input.

**Comment by aenieblas** [comment]
agreed. these require full descriptions of each parameter and advice as to where to find this information.
