### ISSUE TITLE
Information page content (Expert)

### ISSUE THREAD

**Issue by aenieblas** [tokami/StockMonitoringTool#17]
Edit the Length-based workflow information page. Remove extraneous information and outline the broad workflow, following the ‘Considerations’ information, i.e., 
- (Expert) editing the Method Description to that outlined in the Methods Consideration tab , and 
- (Expert) the Data Considerations in the Info page to that outlined in the Data Considerations tab. 
- (Expert) Remove references to ELEFAN and ELEFAN SA except to say that they exist but that Elefan GA is recommended.
- (Dev) Update reference list

*NB: Issues can be fixed by (Expert) = Tobias, (Dev) = qualified shiny developer

**Comment by tokami** [comment]
info page needs some more refinement, but this is the path I would take.
