### ISSUE TITLE
Bin size default and ranges

### ISSUE THREAD

**Issue by tokami** [tokami/StockMonitoringTool#2]
Set bin size default value to 1, and  range to 0.1 and 100. Bin sizes smaller than 1cm might be meaningful for short-lived species. 

https://github.com/tokami/StockMonitoringTool/blob/bad1210832b434e477c157c99addc38066a1dcd2/ui/elefan/elefanGaUI.R#L33

**Comment by tokami** [comment]
adjust step to 0.1

**Comment by aenieblas** [comment]
agreed.
