### ISSUE TITLE
Data aggregation info popup (Expert)

### ISSUE THREAD

**Issue by aenieblas** [tokami/StockMonitoringTool#26]
Is there a recommended length of time/resolution of a length-data set or based on the life history of the species? 1 year if monthly, 1 month if daily? Is there a minimum amount of time that the length data should be distributed over (e.g. 1 year)? 

You note that aggregation over several years will decrease run time - are there any other reasons to aggregate? Please expand the explanation/advise about how to aggregate. 

*NB: Issues can be fixed by (Expert) = Tobias, (Dev) = qualified shiny developer

**Comment by tokami** [comment]
Some more information provided. More elaboration about the minimum length of the data set (e.g. at least a year, in particular for soVBGF) might be considered, but potentially in the data considerations tab rather than under this info button.
