### ISSUE TITLE
Deactivate/hide soVBGF pars

### ISSUE THREAD

**Issue by tokami** [tokami/StockMonitoringTool#3]
https://github.com/tokami/StockMonitoringTool/blob/bad1210832b434e477c157c99addc38066a1dcd2/ui/elefan/elefanGaUI.R#L58

Hide and/or deactivate parameters of the seasonalised VBGF if it is not being used (if clause dependent on "`ELEFAN_GA_seasonalised`"). Do the same for upper bounds of these parameters (lines 73-74).

**Comment by aenieblas** [comment]
agreed.
