### ISSUE TITLE
Method Considerations: assumptions (Expert)

### ISSUE THREAD

**Issue by aenieblas** [tokami/StockMonitoringTool#30]
(Expert) Are these assumptions covered in the “Methods Considerations” tab? If not, and they are valid and useful, please consider adding them: 

- Ensure that your length-frequency data is representative of the full population. (If this is not so, then estimates of fishing mortality will be biased.)
- Ensure that all age groups were sampled.
- Ensure that the sample was from a range of areas where different life histories might live. (e.g., if juveniles occupy nearshore habitat and adults are offshore)
- Ensure that a variety of gears with different selectivities used to collect the samples so that the samples contain multiple age groups.

*NB: Issues can be fixed by (Expert) = Tobias, (Dev) = qualified shiny developer

**Comment by tokami** [comment]
The relevant aspects of this list were included.
