### ISSUE TITLE
Adjust length data fields (Expert)

### ISSUE THREAD

**Issue by aenieblas** [tokami/StockMonitoringTool#45]
(Expert) Adjust length data : bin size will not adjust
What is the reasoning for adjusting the bin size here? It does not adjust, and it does not update when the other bin size field is changed. I recommend removing this box. The same is true for the ‘select years’ field.

**Comment by tokami** [comment]
It might be relevant to adjust the bin size for the length-converted catch curve separately from the bin size for ELEFAN, but this should rarely be the case and makes more sense with individual run buttons for each method. Removed for now.
