### ISSUE TITLE
Make default lower bound data dependent

### ISSUE THREAD

**Issue by tokami** [tokami/StockMonitoringTool#6]
https://github.com/tokami/StockMonitoringTool/blob/bad1210832b434e477c157c99addc38066a1dcd2/ui/elefan/elefanGaUI.R#L53

Default value for lower limit should be data dependent, e.g. 80% of maximum length in the data set. Same is true for default value of upper limit (line 68), e.g. 120% of maximum length.

**Comment by aenieblas** [comment]
ok. suggest replacement code.
