### ISSUE TITLE
Gear selectivity (Expert)

### ISSUE THREAD

**Issue by aenieblas** [tokami/StockMonitoringTool#62]
YPR : gear selectivity have been included in YPR step? I see L50, but not Lc?

You note that “parameters and variables are likely to be stock-specific” - please provide some guidance for the user in their selection.

**Comment by aenieblas** [comment]
(Expert) : You had mentioned in your report that gear selectivity should be incorporated in the data exploration step. Can you give greater detail such that this suggestion can be implemented by any shiny developer?

**Comment by tokami** [comment]
Updated SMT allows to estimate selectivity or specify selectivity based on L50 + L75 or L50 + (L75-L25). That is one step in the right direction. More package development is required to deal with bell-shaped selectivity and to deal with selectivity exploration.
