### ISSUE TITLE
Lm50 and Lm75 possible range (expert)

### ISSUE THREAD

**Issue by aenieblas** [tokami/StockMonitoringTool#64]
Lm50 and Lm75 are both allowed to be negative in the field input and not caught at run check.

To my understanding these should not be negative, correct?

**Comment by tokami** [comment]
That is the disadvantage with `textInput` boxes as UI. The min, max ranges only come into affect when using the little arrows on the side. But you are always allowed to insert negative values if you type them directly.... I will include additional checks and warnings for all parameters
