### ISSUE TITLE
Results captions

### ISSUE THREAD

**Issue by aenieblas** [tokami/StockMonitoringTool#77]
Put the captions for the results figures and tables under each figure and table

**Comment by tokami** [comment]
@aenieblas, each figure and table has a caption, right? But you would like to use the long captions + explanations from the results considerations tab as the captions for the figures and tables and report?

**Comment by aenieblas** [comment]
Yes, it's easier for the user to have the detailed information directly with the figure/table than having to go back and forth, and the captions aren't too long
