### ISSUE TITLE
Description of length indicators - Report

### ISSUE THREAD

**Issue by aenieblas** [tokami/StockMonitoringTool#79]
Table 1 description of parameters should also explain what each relative indicator means. You give examples in the text, e.g., "For example, the indicators could indicate that the proportion of older larger individuals is smaller than expected (red L95% /Linf ), but at the same time the proportion of immature individuals is as expected (green L25% /Lmat )." An explanation of what each relative indicator means when it is red and when it is green would be helpful for users

**Comment by tokami** [comment]
I added more information to the Property column of the table with the parameters.
